version: '2'
services:
  ruby:
    container_name: ruby
    build:
      context: ../../.
      dockerfile: .github/action-test/Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://pericles@postgres/pericles"
  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: pericles
      POSTGRES_DB: pericles
    volumes:
      - postgresql_data:/var/lib/postgresql/data
volumes:
  postgresql_data:

