name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the stack
      run: |
        cd .github/action-test
        docker-compose up -d
    - name: Test
      run: |
        cd .github/action-test
        docker-compose run ruby bundle exec rails test
